name = "Analytical"
uuid = "1f0a6972-6dc4-11ea-3a4f-47f17d9e5175"
authors = ["Lawrence Uricchio", "Jes√∫s Murga-Moreno"]
version = "0.2.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
ParallelUtilities = "fad6cfc8-4f83-11e9-06cc-151124046ad0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
